config/routes.rb
Rails.application.routes.draw do
  mount Motor::Admin => '/motor_admin'
  resources :people, only: :index
  resources :locations, only: :index
  resources :affiliations, only: :index
  resource :importer, only: [:create, :new]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "importers#new"
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  include Queryable
  paginates_per 10

  has_many :person, through: :person_affiliations
  has_many :person_affiliations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concerns/queryable.rb
module Queryable
  extend ActiveSupport::Concern

  class_methods do
    def search(category:, string:)
      if string.blank?
        return self.all
      end

      where_statement = {}
      where_statement[category] = string

      self.where(where_statement)
    end
  end
end

app/models/importer.rb
require'csv'

class Importer
  attr_reader :errors

  def initialize(file)
    @file = file&.open
    @data_list = []
    @errors = {}
  end

  def run
    # refactor
    if @file.blank?
      @errors = ['No file detected']
      return
    end

    CSV.foreach(@file, headers: true).with_index do |row, index|
      next if row['Affiliations'].blank?

      person = build_person(row)
      locations = build_location(row)
      affiliations = build_affiliation(row)

      row = index + 2
      @data_list << { person: person, locations: locations, affiliations: affiliations, row: row }
    end

    @data_list.each do |data|
      insert_to_db!(data)
    end
  end

  def insert_to_db!(data)
    person = data[:person]

    ActiveRecord::Base.transaction do
      locations = data[:locations].map do |l|
        Location.find_or_create_by!(name: l.titleize)
      end

      affiliations = data[:affiliations].map do |a|
        Affiliation.find_or_create_by!(name: a.titleize)
      end

      person.locations = locations
      person.affiliations = affiliations
      person.save!
    end

  rescue ActiveRecord::RecordInvalid => invalid
    row_number = data[:row]

    errors[row_number] = invalid.record.errors.full_messages
  end

  def build_person(row)
    Person.new.tap do |person|
      first_name, last_name = row['Name'].split(' ', 2)

      person.first_name = first_name
      person.last_name = last_name
      person.species = row['Species']&.downcase
      person.gender = row['Gender']&.downcase
      person.weapon = row['Weapon']&.downcase
      person.vehicle = row['Vehicle']&.downcase
    end
  end

  def build_location(row)
    locations_row = row['Location'].split(',')

    locations_row.map { |loc_name| loc_name }
  end

  def build_affiliation(row)
    affiliations_row = row['Affiliations'].split(',')

    affiliations_row.map { |aff_name| aff_name.downcase }
  end
end

app/models/location.rb
class Location < ApplicationRecord
  include Queryable
  paginates_per 10

  has_many :person, through: :person_locations
  has_many :person_locations

  before_save :titleize_name

  def titleize_name
    self.name = name&.titleize
  end
end

app/models/person.rb
class Person < ApplicationRecord
  include Queryable
  paginates_per 10

  has_many :person_locations
  has_many :locations, through: :person_locations

  has_many :person_affiliations
  has_many :affiliations, through: :person_affiliations

  validates :first_name, presence: true

  before_save :titleize_name

  def titleize_name
    if first_name.present?
      self.first_name = first_name.split(' ').map(&:upcase_first).join(' ')
    end

    if last_name.present?
      self.last_name = last_name.split(' ').map(&:upcase_first).join(' ')
    end
  end
end

app/models/person_affiliation.rb
class PersonAffiliation < ApplicationRecord
  belongs_to :person
  belongs_to :affiliation
end

app/models/person_location.rb
class PersonLocation < ApplicationRecord
  belongs_to :person
  belongs_to :location
end

app/controllers/affiliations_controller.rb
class AffiliationsController < ApplicationController
  def index
    @affiliations = Affiliation
      .search(category: params[:category], string: params[:search])
      .order(params[:sort])
      .page(params[:page])
    @categories = Affiliation.column_names.reject { |name| %w(id created_at updated_at).include?(name) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/importers_controller.rb
class ImportersController < ApplicationController
  def new
  end

  def create
    importer = Importer.new(params[:csv])
    importer.run

    if importer.errors.present? 
      flash[:alert] = importer.errors
    else
      flash[:success] = 'Successful Upload'
    end

    redirect_to new_importer_path
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location
      .search(category: params[:category], string: params[:search])
      .order(params[:sort])
      .page(params[:page])
    @categories = Location.column_names.reject { |name| %w(id created_at updated_at).include?(name) }
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person
      .search(category: params[:category], string: params[:search])
      .order(params[:sort])
      .page(params[:page])
    @categories = Person.column_names.reject { |name| %w(id created_at updated_at).include?(name) }
  end
end

app/helpers/affiliations_helper.rb
module AffiliationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/importer_helper.rb
module ImporterHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/affiliations/index.html.erb
<div class='container h-screen flex-row space-y-8'>
  <h1 class="font-bold text-4xl">Affiliations#index</h1>
  <p>Find me in app/views/affiliations/index.html.erb</p>

  <%= render partial: 'shared/body', locals: { resources: @affiliations, categories: @categories } %>
</div>

app/views/importers/_error_alert.html.erb
<div id="alert-additional-content-2" class="p-4 mb-4 text-red-800 border border-red-300 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400 dark:border-red-800" role="alert">
  <div class="flex items-center">
    <svg class="flex-shrink-0 w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <h3 class="text-lg font-medium">Error</h3>
  </div>
  <div class="mt-2 mb-4 text-sm">
    <ol>
      <% errors.each do |k, v| %>
        <li><%= "Row #{k}: #{v}" %></li>
      <% end %>
    </ol>
  </div>
</div>

app/views/importers/_success_alert.html.erb
<div id="alert-additional-content-3" class="p-4 mb-4 text-green-800 border border-green-300 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400 dark:border-green-800" role="alert">
  <div class="flex items-center">
    <svg class="flex-shrink-0 w-4 h-4 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
    </svg>
    <span class="sr-only">Info</span>
    <h3 class="text-lg font-medium">Success</h3>
  </div>
  <div class="mt-2 mb-4 text-sm">
    <%= msg %>
  </div>
</div>

app/views/importers/create.html.erb
<h1>Importer#create</h1>
<p>Find me in app/views/importer/create.html.erb</p>

app/views/importers/new.html.erb
<div class='container h-screen'>
  <% flash&.each do |key, value| %>
    <% if key == 'alert' %>
      <%= render 'error_alert', errors: value %>
    <% elsif key == 'success' %>
      <%= render 'success_alert', msg: value %>
    <% end %>
  <% end %>


  <h1 class='text-5xl font-extrabold'>Please import CSV here</h1>

  <%= form_tag importer_path, multipart: true do %>
    <div>
      <%= file_field_tag :csv, accept: 'text/csv' %>
    </div>

    <div>
      <%= submit_tag :submit, class: 'bg-sky-500 hover:bg-sky-700 px-5 py-2 text-sm leading-5 rounded-full font-semibold text-white' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sentia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="mx-auto px-5 flex-row space-y-10">
      <nav class="border-gray-200 bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <button data-collapse-toggle="navbar-solid-bg" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-solid-bg" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
            </svg>
          </button>
          <div class="hidden w-full md:block md:w-auto" id="navbar-solid-bg">
            <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
              <li>
                <%= link_to 'Importer', new_importer_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
              </li>
              <li>
                <%= link_to 'People', people_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
              </li>
              <li>
                <%= link_to 'Locations', locations_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
              </li>
              <li>
                <%= link_to 'Affiliations', affiliations_path, class: "block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
    </main>
  </body>
</html>

app/views/locations/index.html.erb
<div class='container h-screen flex-row space-y-8'>
  <h1 class="font-bold text-4xl">Locations#index</h1>
  <p>Find me in app/views/locations/index.html.erb</p>

  <%= render partial: 'shared/body', locals: { resources: @locations, categories: @categories } %>
</div>

app/views/people/_person.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
  <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
    <%= person.first_name %>
  </th>
  <td class="px-6 py-4">
    <%= person.last_name %>
  </td>
  <td class="px-6 py-4">
    <%= person.weapon %>
  </td>
  <td class="px-6 py-4">
    <%= person.vehicle %>
  </td>
  <td class="px-6 py-4">
    <%= person.species %>
  </td>
  <td class="px-6 py-4">
    <%= person.gender %>
  </td>
</tr>

app/views/people/index.html.erb
<div class='container h-screen flex-row space-y-8'>
  <h1 class='text-5xl font-extrabold'>Persons#index</h1>
  <p>Find me in app/views/persons/index.html.erb</p>
  <form class="flex flex-col md:flex-row gap-3">
    <div class="flex">
      <%= text_field_tag :search, nil, placeholder: "Search...", class: "w-full md:w-80 px-3 h-10 rounded-l border-2 border-sky-500 focus:outline-none focus:border-sky-500" %>
      <button type="submit" class="bg-sky-500 text-white rounded-r px-2 md:px-3 py-0 md:py-1">Search</button>
    </div>
    <%= select_tag "category", options_for_select(@categories, @categories.first) %>
  </form>
  <div class='border-2 border-gray-400'>
    <%= paginate @people %>
  </div>
  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr>
          <% @categories.each do |c| %>
            <th scope="col" class="px-6 py-3">
              <%= link_to c.titleize, sort: c %>
            </th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <%= render partial: :person, collection: @people, locals: { categories: @categories } %>
      </tbody>
    </table>
  </div>
</div>

app/views/shared/_body.html.erb
<form class="flex flex-col md:flex-row gap-3">
  <div class="flex">
    <%= text_field_tag :search, nil, placeholder: "Search...", class: "w-full md:w-80 px-3 h-10 rounded-l border-2 border-sky-500 focus:outline-none focus:border-sky-500" %>
    <button type="submit" class="bg-sky-500 text-white rounded-r px-2 md:px-3 py-0 md:py-1">Search</button>
  </div>
  <%= select_tag "category", options_for_select(categories, categories.first) %>

</form>

<%= render partial: 'shared/table', locals: { resources: resources, categories: categories } %>

app/views/shared/_table.html.erb
<div class='border-2 border-gray-400'>
  <%= paginate resources %>
</div>

<div class="relative overflow-x-auto">
  <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <% categories.each do |c| %>
          <th scope="col" class="px-6 py-3">
            <%= link_to c.titleize, sort: c %>
          </th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% resources.each do |r| %>
        <%= render partial: 'shared/table_items', locals: { resource: r, categories: categories } %>
      <% end %>
    </tbody>

  </table>
</div>

app/views/shared/_table_items.html.erb
<tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
  <% categories.each do |c| %>
    <td class="px-6 py-4">
      <%= resource[c] %>
    </td>
  <% end %>
</tr>